<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 3.5.1 setup script
 * Date: Thu, 31 May 2012 05:39:29 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: mysql-j.sourceforge.net [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'mysql-j';
$cfg['Servers'][$i]['host'] = 'mysql-j';
//$cfg['Servers'][$i]['port'] = 4040;
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'j760788admin';
$cfg['Servers'][$i]['password'] = '013579';
$cfg['Servers'][$i]['ssl'] = true;

/* End of servers configuration */

$cfg['blowfish_secret'] = '4fc703e050f6a5.97296630';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>