package resources;

public class TsInviteCause {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_invite_cause.id
     *
     * @mbggenerated Tue Feb 28 17:12:17 CST 2012
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_invite_cause.reason
     *
     * @mbggenerated Tue Feb 28 17:12:17 CST 2012
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_invite_cause.link
     *
     * @mbggenerated Tue Feb 28 17:12:17 CST 2012
     */
    private String link;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_invite_cause.hobby
     *
     * @mbggenerated Tue Feb 28 17:12:17 CST 2012
     */
    private String hobby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_invite_cause.contact
     *
     * @mbggenerated Tue Feb 28 17:12:17 CST 2012
     */
    private String contact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_invite_cause.status
     *
     * @mbggenerated Tue Feb 28 17:12:17 CST 2012
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_invite_cause.id
     *
     * @return the value of ts_invite_cause.id
     *
     * @mbggenerated Tue Feb 28 17:12:17 CST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_invite_cause.id
     *
     * @param id the value for ts_invite_cause.id
     *
     * @mbggenerated Tue Feb 28 17:12:17 CST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_invite_cause.reason
     *
     * @return the value of ts_invite_cause.reason
     *
     * @mbggenerated Tue Feb 28 17:12:17 CST 2012
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_invite_cause.reason
     *
     * @param reason the value for ts_invite_cause.reason
     *
     * @mbggenerated Tue Feb 28 17:12:17 CST 2012
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_invite_cause.link
     *
     * @return the value of ts_invite_cause.link
     *
     * @mbggenerated Tue Feb 28 17:12:17 CST 2012
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_invite_cause.link
     *
     * @param link the value for ts_invite_cause.link
     *
     * @mbggenerated Tue Feb 28 17:12:17 CST 2012
     */
    public void setLink(String link) {
        this.link = link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_invite_cause.hobby
     *
     * @return the value of ts_invite_cause.hobby
     *
     * @mbggenerated Tue Feb 28 17:12:17 CST 2012
     */
    public String getHobby() {
        return hobby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_invite_cause.hobby
     *
     * @param hobby the value for ts_invite_cause.hobby
     *
     * @mbggenerated Tue Feb 28 17:12:17 CST 2012
     */
    public void setHobby(String hobby) {
        this.hobby = hobby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_invite_cause.contact
     *
     * @return the value of ts_invite_cause.contact
     *
     * @mbggenerated Tue Feb 28 17:12:17 CST 2012
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_invite_cause.contact
     *
     * @param contact the value for ts_invite_cause.contact
     *
     * @mbggenerated Tue Feb 28 17:12:17 CST 2012
     */
    public void setContact(String contact) {
        this.contact = contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_invite_cause.status
     *
     * @return the value of ts_invite_cause.status
     *
     * @mbggenerated Tue Feb 28 17:12:17 CST 2012
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_invite_cause.status
     *
     * @param status the value for ts_invite_cause.status
     *
     * @mbggenerated Tue Feb 28 17:12:17 CST 2012
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}