package com.nianmi.member.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import resources.TsInviteCause;
import resources.TsInviteCauseExample;

public interface TsInviteCauseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_invite_cause
     *
     * @mbggenerated Tue Feb 28 17:12:17 CST 2012
     */
    int countByExample(TsInviteCauseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_invite_cause
     *
     * @mbggenerated Tue Feb 28 17:12:17 CST 2012
     */
    int deleteByExample(TsInviteCauseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_invite_cause
     *
     * @mbggenerated Tue Feb 28 17:12:17 CST 2012
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_invite_cause
     *
     * @mbggenerated Tue Feb 28 17:12:17 CST 2012
     */
    int insert(TsInviteCause record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_invite_cause
     *
     * @mbggenerated Tue Feb 28 17:12:17 CST 2012
     */
    int insertSelective(TsInviteCause record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_invite_cause
     *
     * @mbggenerated Tue Feb 28 17:12:17 CST 2012
     */
    List<TsInviteCause> selectByExample(TsInviteCauseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_invite_cause
     *
     * @mbggenerated Tue Feb 28 17:12:17 CST 2012
     */
    TsInviteCause selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_invite_cause
     *
     * @mbggenerated Tue Feb 28 17:12:17 CST 2012
     */
    int updateByExampleSelective(@Param("record") TsInviteCause record, @Param("example") TsInviteCauseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_invite_cause
     *
     * @mbggenerated Tue Feb 28 17:12:17 CST 2012
     */
    int updateByExample(@Param("record") TsInviteCause record, @Param("example") TsInviteCauseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_invite_cause
     *
     * @mbggenerated Tue Feb 28 17:12:17 CST 2012
     */
    int updateByPrimaryKeySelective(TsInviteCause record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_invite_cause
     *
     * @mbggenerated Tue Feb 28 17:12:17 CST 2012
     */
    int updateByPrimaryKey(TsInviteCause record);
}